server:
  port: 8763

spring:
  profiles: dev
  application:
    name: eureka-sv
  profile: prod

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761

config:
  log-path: /home/rkritchat/Desktop/ep-corpt/logs